#!/bin/bash

# Liste des adresses IP ou noms d'hôtes des machines cibles 
machines=("172.16.20.100" "172.16.20.101" "172.16.20.102" "172.16.20.103" "172.16.20.107" "172.16.20.105" "172.16.20.108" "172.16.20.106" "172.16.20.109")

# Chemin du répertoire d'installation du Node Exporter sur les machines cibles
installation_path="/opt/node_exporter"

# Commande d'installation et de démarrage du Node Exporter
install_command="wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.darwin-amd64.tar.gz && tar xvfz node_exporter-2.3.1.linux-amd64.tar.gz && cd node_exporter-2.3.1.linux-amd64 && ./node_exporter"  

# Boucle sur la liste des machines cibles
for machine in "${machines[@]}"
do
    echo "Déploiement sur la machine : $machine"
    
    # Connexion SSH à la machine cible et exécution de la commande d'installation
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$machine "$install_command"
    
    echo "Déploiement terminé sur la machine : $machine"
    echo ""
done

echo "Déploiement sur toutes les machines terminé."
